"""Add is_active field to events

Revision ID: 258ea8e7e896
Revises: ae481df4769c
Create Date: 2025-11-20 21:29:04.334586

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "258ea8e7e896"
down_revision: Union[str, Sequence[str], None] = "ae481df4769c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "is_active")
    # ### end Alembic commands ###
