"""Add check_in_token and checked_in_at fields

Revision ID: 6cdded4601f6
Revises: c7cc80e34d1c
Create Date: 2025-11-21 19:37:48.727476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6cdded4601f6"
down_revision: Union[str, Sequence[str], None] = "c7cc80e34d1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем check_in_token с временным дефолтным значением для существующих записей
    op.add_column(
        "registrations",
        sa.Column("check_in_token", sa.String(length=64), nullable=True),
    )

    # Генерируем токены для существующих записей
    op.execute(
        """
        UPDATE registrations 
        SET check_in_token = 'legacy_' || id::text || '_' || md5(random()::text)
        WHERE check_in_token IS NULL
    """
    )

    # Теперь делаем поле NOT NULL
    op.alter_column("registrations", "check_in_token", nullable=False)

    op.add_column(
        "registrations", sa.Column("checked_in_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_registrations_check_in_token"),
        "registrations",
        ["check_in_token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_registrations_check_in_token"), table_name="registrations")
    op.drop_column("registrations", "checked_in_at")
    op.drop_column("registrations", "check_in_token")
    # ### end Alembic commands ###
