"""Add unique constraints

Revision ID: 6d5f5d60dac2
Revises: 6cdded4601f6
Create Date: 2025-11-21 20:55:59.401692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6d5f5d60dac2"
down_revision: Union[str, Sequence[str], None] = "6cdded4601f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_events_single_active",
        "events",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_unique_constraint(
        "uq_user_event_registration", "registrations", ["user_id", "event_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_event_registration", "registrations", type_="unique")
    op.drop_index(
        "ix_events_single_active",
        table_name="events",
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###
