"""Changing models

Revision ID: ae481df4769c
Revises: f13df89881be
Create Date: 2025-11-20 20:32:41.830807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae481df4769c'
down_revision: Union[str, Sequence[str], None] = 'f13df89881be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('deadline', sa.DateTime(), nullable=False))
    op.drop_column('events', 'max_participants')
    op.drop_column('events', 'is_published')
    op.drop_column('events', 'is_active')
    op.drop_column('registrations', 'comment')
    op.add_column('users', sa.Column('telegram_username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('isu', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_telegram_username'), 'users', ['telegram_username'], unique=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_telegram_username'), table_name='users')
    op.drop_column('users', 'isu')
    op.drop_column('users', 'telegram_username')
    op.add_column('registrations', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('events', 'deadline')
    # ### end Alembic commands ###
