"""Add status field to registration

Revision ID: c7cc80e34d1c
Revises: 258ea8e7e896
Create Date: 2025-11-21 18:26:20.370942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7cc80e34d1c"
down_revision: Union[str, Sequence[str], None] = "258ea8e7e896"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем enum тип
    registrationstatus_enum = sa.Enum(
        "PENDING", "ACCEPTED", "DECLINED", "CANCELLED", name="registrationstatus"
    )
    registrationstatus_enum.create(op.get_bind(), checkfirst=True)

    # Добавляем колонку с дефолтным значением для существующих записей
    op.add_column(
        "registrations",
        sa.Column(
            "status", registrationstatus_enum, nullable=False, server_default="PENDING"
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registrations", "status")

    # Удаляем enum тип
    sa.Enum(name="registrationstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
